let bgMapUrl = window.serviceUrl.mapDataUrl;
bgMapUrl += 'arcgis/rest/services/YX01/MapServer';
const layers = {
  baseLayer: bgMapUrl,
  FeatureLayers: [
    { name: '可燃气体探测设备', visible: false, url: `${bgMapUrl}/1`, order: 1 },
    { name: '有毒气体探测设备', visible: false, url: `${bgMapUrl}/2`, order: 2 },
    { name: '感烟探测器', visible: false, url: `${bgMapUrl}/3`, order: 3 },
    { name: '红外对射', visible: false, url: `${bgMapUrl}/4`, order: 4 },
    { name: '感温探测器', visible: false, url: `${bgMapUrl}/5` },
    { name: '火焰探测器', visible: false, url: `${bgMapUrl}/6` },
    { name: '手动报警按钮', visible: false, url: `${bgMapUrl}/7` },
    { name: '感温电缆', visible: false, url: `${bgMapUrl}/8` },
    { name: '声光', visible: false, url: `${bgMapUrl}/9` },
    { name: '光纤光栅', visible: false, url: `${bgMapUrl}/10` },
    { name: '防火阀', visible: false, url: `${bgMapUrl}/11` },
    { name: '控制阀', visible: false, url: `${bgMapUrl}/12` },
    { name: '信号阀', visible: false, url: `${bgMapUrl}/13` },
    { name: '报警控制器', visible: false, url: `${bgMapUrl}/14` },
    { name: '图形控制站', visible: false, url: `${bgMapUrl}/15` },
    { name: '压力开关', visible: false, url: `${bgMapUrl}/16` },
    { name: '消防水泵', visible: false, url: `${bgMapUrl}/17` },
    { name: '消防水池', visible: false, url: `${bgMapUrl}/18` },
    { name: '消火栓', visible: false, url: `${bgMapUrl}/19` },
    { name: '消防管网', visible: false, url: `${bgMapUrl}/20` },
    { name: '消防水炮', visible: false, url: `${bgMapUrl}/21` },
    { name: '消防控制台', visible: false, url: `${bgMapUrl}/22` },
    { name: '泡沫罐', visible: false, url: `${bgMapUrl}/23` },
    { name: '自喷淋保护区域', visible: false, url: `${bgMapUrl}/24` },
    { name: '泡沫泵', visible: false, url: `${bgMapUrl}/25` },
    { name: '泡沫栓', visible: false, url: `${bgMapUrl}/26` },
    { name: '泡沫管网', visible: false, url: `${bgMapUrl}/27` },
    { name: '泡沫炮', visible: false, url: `${bgMapUrl}/28` },
    { name: '灭火器手提式', visible: false, url: `${bgMapUrl}/29` },
    { name: '泡沫系统保护区域', visible: false, url: `${bgMapUrl}/30` },
    { name: '气体灭火系统保护区域', visible: false, url: `${bgMapUrl}/31` },
    { name: '干粉灭火系统保护区域', visible: false, url: `${bgMapUrl}/32` },
    { name: '灭火器推车式', visible: false, url: `${bgMapUrl}/33` },
    { name: '灭火设施存放点位', visible: false, url: `${bgMapUrl}/34` },
    { name: '放射源', visible: false, url: `${bgMapUrl}/35` },
    { name: '仓库', visible: false, url: `${bgMapUrl}/36` },
    { name: '储罐', visible: false, url: `${bgMapUrl}/37` },
    { name: '大机组', visible: false, url: `${bgMapUrl}/38` },
    { name: 'A类设备', visible: false, url: `${bgMapUrl}/39` },
    { name: '塔容器', visible: false, url: `${bgMapUrl}/40` },
    { name: '洗眼器', visible: false, url: `${bgMapUrl}/41` },
    { name: '空气呼吸器', visible: false, url: `${bgMapUrl}/42` },
    { name: '工业视频', visible: false, url: `${bgMapUrl}/43` },
    { name: '门禁', visible: false, url: `${bgMapUrl}/44` },
    { name: '周界', visible: false, url: `${bgMapUrl}/45` },
    { name: '扩音对讲', id: 'test', visible: false, url: `${bgMapUrl}/46` },
    { name: '周界基地设备', visible: false, url: `${bgMapUrl}/47` },
    { name: '火炬', visible: false, url: `${bgMapUrl}/48` },
    { name: '监测井', visible: false, url: `${bgMapUrl}/49` },
    { name: '污水泵', visible: false, url: `${bgMapUrl}/50` },
    { name: '污水池 ', visible: false, url: `${bgMapUrl}/51` },
    { name: '路灯', visible: false, url: `${bgMapUrl}/52` },
    { name: '井盖', visible: false, url: `${bgMapUrl}/53` },
    { name: '阀门井', visible: false, url: `${bgMapUrl}/54` },
    { name: '雨水篦子', visible: false, url: `${bgMapUrl}/55` },
    { name: '雨水池', visible: false, url: `${bgMapUrl}/56` },
    { name: '厂内管廊', visible: false, url: `${bgMapUrl}/57` },
    { name: '装车站', visible: false, url: `${bgMapUrl}/58` },
    { name: '火车装卸', visible: false, url: `${bgMapUrl}/59` },
    { name: '厂区围墙', visible: true, url: `${bgMapUrl}/61` },
    { name: '道路', visible: true, url: `${bgMapUrl}/62` },
    { name: '道路中心线', visible: true, url: `${bgMapUrl}/63` },
    { name: '罐区', visible: false, url: `${bgMapUrl}/64` },
    { name: '建筑物', visible: true, url: `${bgMapUrl}/65`, order: 69 },
    { name: '扩音分区', visible: true, url: `${bgMapUrl}/66`, order: 70 },
    { name: '铁路', visible: true, url: `${bgMapUrl}/67`, order: 71 },
    { name: '植被', visible: true, url: `${bgMapUrl}/68`, order: 72 },
    { name: '单元界区', visible: false, url: `${bgMapUrl}/69`, order: 73, maxScale: 7400 },
    { name: '装置界区', visible: false, url: `${bgMapUrl}/70`, order: 74, maxScale: 7400 },
    { name: '分部界区', visible: false, url: `${bgMapUrl}/71`, order: 75, maxScale: 7400 },
    { name: '门禁分区', visible: false, url: `${bgMapUrl}/72`, order: 76 },
    { name: '疏散路线', visible: false, url: `${bgMapUrl}/73`, order: 77 },
    { name: '重大危险源', visible: false, url: `${bgMapUrl}/74`, order: 78 },
    { name: '外排口', visible: false, url: `${bgMapUrl}/75`, order: 79 },
    { name: '裂解炉', visible: false, url: `${bgMapUrl}/76`, order: 80 },
    { name: '超高压蒸汽管网', visible: false, url: `${bgMapUrl}/77`, order: 81 },
    { name: '高压蒸汽管网', visible: false, url: `${bgMapUrl}/78`, order: 82 },
    { name: '中压蒸汽管网', visible: false, url: `${bgMapUrl}/79`, order: 83 },
    { name: '低压蒸汽管网', visible: false, url: `${bgMapUrl}/80`, order: 84 },
    { name: '水管网', visible: false, url: `${bgMapUrl}/81`, order: 85 },
    { name: '水探测点位', visible: false, url: `${bgMapUrl}/82`, order: 86 },
    { name: '高压蒸汽点位', visible: false, url: `${bgMapUrl}/83`, order: 87 },
    { name: '中压蒸汽点位', visible: false, url: `${bgMapUrl}/84`, order: 89 },
    { name: '低压蒸汽点位', visible: false, url: `${bgMapUrl}/85`, order: 90 },
  ] };

export default layers;
