export const fakeData = [
  {
    // 质量日报固定数据
    // 指令日报原料
    // itemRowSpan: 分析项目合并行
    // sampleRowSpan:原料名称与罐号/批号合并行
    limisRawMaterial: [
      { key: 1, sampleRowSpan: 11, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: null, name: '密度（20℃）/（kg/m3）', nameSearchValue: ['密度(20℃)'] },
      { key: 2, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '馏程/℃', itemRowSpan: 3, name: '初馏点', nameSearchValue: ['初馏点'] },
      { key: 3, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '馏程/℃', itemRowSpan: 0, name: '馏程50%', nameSearchValue: ['馏程50%'] },
      { key: 4, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '馏程/℃', itemRowSpan: 0, name: '终馏点', nameSearchValue: ['终馏点'] },
      { key: 5, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 5, name: '烷烃（P）含量', nameSearchValue: ['烷烃'] },
      { key: 6, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '正构烷烃（n-P）含量', nameSearchValue: ['正构烷烃'] },
      { key: 7, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '烯烃（O）含量', nameSearchValue: ['烯烃'] },
      { key: 8, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '芳香烃（A）含量', nameSearchValue: ['芳烃'] },
      { key: 9, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '环烷烃（N）含量', nameSearchValue: ['环烷烃'] },
      { key: 10, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: null, name: '硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 11, sampleRowSpan: 0, sampleName: '石脑油', sampleSearchValue: ['石脑油'], item: null, name: '含氧化合物/（mg/kg）', nameSearchValue: ['氧化物'] },
      { key: 12, sampleRowSpan: 5, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总烷烃/ %（体积分数）', nameSearchValue: ['总烷烃'] },
      { key: 13, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总烯烃/ %（体积分数）', nameSearchValue: ['总烯烃'] },
      { key: 14, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '丙烷/%+正丁烷/%（体积分数）', nameSearchValue: ['丙烷+正丁烷'] },
      { key: 15, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '碳五及碳五以上/%（体积分数）', nameSearchValue: ['C5及以上'] },
      { key: 16, sampleRowSpan: 0, sampleName: '轻烃', sampleSearchValue: ['轻烃（丙烷+LPG）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 17, sampleRowSpan: 6, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 5, name: '烷烃（P）含量', nameSearchValue: ['烷烃'] },
      { key: 18, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '正构烷烃（n-P）含量', nameSearchValue: ['正构烷烃'] },
      { key: 19, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '烯烃（O）含量', nameSearchValue: ['烯烃'] },
      { key: 20, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '芳香烃（A）含量', nameSearchValue: ['芳烃'] },
      { key: 21, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油'], item: '族组成（PONA值，质量分数）/%', itemRowSpan: 0, name: '环烷烃（N）含量', nameSearchValue: ['环烷烃'] },
      { key: 22, sampleRowSpan: 0, sampleName: '碳五拔头油', sampleSearchValue: ['大连-碳五拔头油', '东营-碳五拔头油'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['硫'] },
      { key: 23, sampleRowSpan: 4, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '乙烷含量/%（体积分数）', nameSearchValue: ['乙烷'] },
      { key: 24, sampleRowSpan: 0, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '碳三及以上烃类/ %（体积分数）', nameSearchValue: ['C3和C3以上烃类'] },
      { key: 25, sampleRowSpan: 0, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '不饱和烃类/ %（体积分数）', nameSearchValue: ['不饱和烃类'] },
      { key: 26, sampleRowSpan: 0, sampleName: '富乙烷气（凯顺）', sampleSearchValue: ['富乙烷气（凯顺样）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 27, sampleRowSpan: 4, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '丙烷/ %（体积分数）', nameSearchValue: ['丙烷'] },
      { key: 28, sampleRowSpan: 0, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '总烯烃/ %（体积分数）', nameSearchValue: ['总烯烃'] },
      { key: 29, sampleRowSpan: 0, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '碳四及以上烃类/ %（体积分数）', nameSearchValue: ['C5及以上'] },
      { key: 30, sampleRowSpan: 0, sampleName: '液化丙烷（凯顺）', sampleSearchValue: ['液化丙烷（凯顺样）'], item: null, name: '总硫含量/（mg/kg）', nameSearchValue: ['总硫'] },
      { key: 31, sampleRowSpan: 4, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '氢气/ %（体积分数）', nameSearchValue: ['氢气'] },
      { key: 32, sampleRowSpan: 0, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '氮气/%（体积分数）', nameSearchValue: ['氮气'] },
      { key: 33, sampleRowSpan: 0, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '甲烷/%（体积分数）', nameSearchValue: ['甲烷'] },
      { key: 34, sampleRowSpan: 0, sampleName: '工业用氢气（凯顺）', sampleSearchValue: ['工业用氢气（凯顺样）'], item: null, name: '乙烷+乙烯/ %（体积分数）', nameSearchValue: ['乙烷+乙烯'] },
      { key: 35, sampleRowSpan: 7, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '乙烯含量/%（体积分数）', nameSearchValue: ['乙烯'] },
      { key: 36, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '丙烷含量/ %（体积分数）', nameSearchValue: ['丙烷'] },
      { key: 37, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '丙烯含量/ %（体积分数）', nameSearchValue: ['丙烯'] },
      { key: 38, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: 'C4和C4以上含量/ %（体积分数）', nameSearchValue: ['C4和C4以上含量'] },
      { key: 39, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '一氧化碳含量/ %（体积分数）', nameSearchValue: ['一氧化碳含量'] },
      { key: 40, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '二氧化碳含量/ %（体积分数）', nameSearchValue: ['二氧化碳含量'] },
      { key: 41, sampleRowSpan: 0, sampleName: '富乙烯气', sampleSearchValue: ['富乙烯气'], item: null, name: '总硫含量/ %（体积分数）', nameSearchValue: ['总硫'] },
      { key: 42, sampleRowSpan: 6, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '全水分Mt/%', nameSearchValue: ['全水分Mt/%'] },
      { key: 43, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '干燥基灰分Ad/％', nameSearchValue: ['干燥基灰分Ad/％'] },
      { key: 44, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '干燥无灰基挥发分Vdaf/%', nameSearchValue: ['干燥无灰基挥发分Vdaf/%'] },
      { key: 45, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '空干基高位发热量Qgr，ad/kcal/kg', nameSearchValue: ['空干基高位发热量Qgr，ad/kcal/kg'] },
      { key: 46, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '收到基低位热值Qnet，ar/kcal/kg', nameSearchValue: ['收到基低位热值Qnet，ar/kcal/kg'] },
      { key: 47, sampleRowSpan: 0, sampleName: '入厂煤', sampleSearchValue: ['入厂煤'], item: null, name: '干燥基全硫St，d/%', nameSearchValue: ['干燥基全硫St，d/%'] },
    ],
    // 质量日报 -> 中控 -> 馏出口
    outlet: [
      { key: 1, locationRowSpan: 16, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['一氧化碳'], name: '一氧化碳/（ml/m³）' },
      { key: 2, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['二氧化碳'], name: '二氧化碳/（ml/m³）' },
      { key: 3, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['氢气'], name: '氢气/ %（体积分数）' },
      { key: 4, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['氢气'], sampleName: '氢气', item: null, nameSearchValue: ['乙烷+乙烯'], name: '乙烷+乙烯/ %（体积分数）' },
      { key: 5, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['乙烯'], name: '乙烯含量/%（体积分数） ' },
      { key: 6, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['碳三及以上馏分'], name: 'C3和C3以上含量/（ml/m3）' },
      { key: 7, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['乙炔'], name: '乙炔含量/（ml/m3）' },
      { key: 8, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['液相乙烯'], sampleName: '乙烯', item: null, nameSearchValue: ['甲烷+乙烷'], name: '硫含量/（mg/kg）' },
      { key: 9, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['丙烯'], name: '丙烯含量/ %（体积分数）' },
      { key: 10, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['甲基乙炔+丙二烯'], name: '甲基乙炔+丙二烯含量/ %（质量分数）' },
      { key: 11, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['丁二烯'], name: '丁烯/ %（质量分数）' },
      { key: 12, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['丙烯'], sampleName: '丙烯', item: null, nameSearchValue: ['硫'], name: '碳五及以上/ %（质量分数）' },
      { key: 13, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 4, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['C3'], name: '碳三/ %（质量分数）' },
      { key: 14, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['丁二烯'], name: '丁二烯/ %（质量分数）' },
      { key: 15, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['丁烯'], name: '丁烯/ %（质量分数）' },
      { key: 16, locationRowSpan: 0, locationSearchValue: ['乙烯-裂解急冷', '乙烯-压缩分离'], location: '裂解装置', sampleRowSpan: 0, sampleSearchValue: ['混合C4'], sampleName: '混合碳四', item: null, nameSearchValue: ['C5及C5以上'], name: '碳五及以上/ %（质量分数）' },
      { key: 16, locationRowSpan: 6, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 4, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['1,3-丁二烯'], name: '丁二烯含量/ %（质量分数）' },
      { key: 17, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['总炔'], name: '总炔含量/（mg/kg）' },
      { key: 18, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['乙烯基乙炔'], name: '乙烯基乙炔含量/（mg/kg）' },
      { key: 19, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['丁二烯产品'], sampleName: '丁二烯', item: null, nameSearchValue: ['TBC含量'], name: 'TBC含量/（mg/kg）' },
      { key: 20, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 2, sampleSearchValue: ['抽余C4'], sampleName: '抽余碳四', item: null, nameSearchValue: ['1,3-丁二烯'], name: '1,3-丁二烯含量/（mg/kg）' },
      { key: 21, locationRowSpan: 0, locationSearchValue: ['丁二烯'], location: '丁二烯抽提装置', sampleRowSpan: 0, sampleSearchValue: ['抽余C4'], sampleName: '抽余碳四', item: null, nameSearchValue: ['乙腈'], name: '乙腈含量/（mg/kg）' },
      { key: 22, locationRowSpan: 4, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 2, sampleSearchValue: ['MTBE产品'], sampleName: 'MTBE', item: null, nameSearchValue: ['甲基叔丁基醚+甲基仲丁基醚+C5'], name: '甲基叔丁基醚+‎甲基仲丁基‎醚‎/ %（质量分数）' },
      { key: 23, locationRowSpan: 0, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 0, sampleSearchValue: ['MTBE产品'], sampleName: 'MTBE', item: null, nameSearchValue: ['甲醇'], name: '甲醇/ %（质量分数）' },
      { key: 24, locationRowSpan: 0, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 2, sampleSearchValue: ['丁烯-1产品'], sampleName: '丁烯-1', item: null, nameSearchValue: ['1-丁烯'], name: '丁烯-1纯度/ %（质量分数）' },
      { key: 25, locationRowSpan: 0, locationSearchValue: ['MTBE/丁烯-1'], location: 'MTBE/丁烯-1装置', sampleRowSpan: 0, sampleSearchValue: ['丁烯-1产品'], sampleName: '丁烯-1', item: null, nameSearchValue: ['1,3-丁二烯+丙二烯'], name: '丁二烯+丙二烯/（mg/kg）' },
      { key: 26, locationRowSpan: 4, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 2, sampleSearchValue: ['苯产品'], sampleName: '苯', item: null, nameSearchValue: ['苯'], name: '纯度/%（质量分数）' },
      { key: 27, locationRowSpan: 0, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 0, sampleSearchValue: ['苯产品'], sampleName: '苯', item: null, nameSearchValue: ['苯结晶点'], name: '结晶点/℃' },
      { key: 28, locationRowSpan: 0, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 1, sampleSearchValue: ['甲苯产品'], sampleName: '甲苯', item: null, nameSearchValue: ['甲苯'], name: '纯度/%（质量分数）' },
      { key: 29, locationRowSpan: 0, locationSearchValue: ['芳烃'], location: '芳烃抽提装置', sampleRowSpan: 1, sampleSearchValue: ['混合二甲苯产品'], sampleName: '混合二甲苯', item: null, nameSearchValue: ['乙苯+二甲苯'], name: '二甲苯/%（质量分数）' },
      { key: 30, locationRowSpan: 3, locationSearchValue: ['汽油加氢装置'], location: '加氢装置', sampleRowSpan: 3, sampleSearchValue: ['C6-C8产品汽油'], sampleName: '加氢汽油', item: null, nameSearchValue: ['C5'], name: '碳五/ %（质量分数）' },
      { key: 31, locationRowSpan: 0, locationSearchValue: ['汽油加氢装置'], location: '加氢装置', sampleRowSpan: 0, sampleSearchValue: ['C6-C8产品汽油'], sampleName: '加氢汽油', item: null, nameSearchValue: ['C9以上芳烃'], name: '碳九及以上芳烃/ %(质量分数)' },
      { key: 32, locationRowSpan: 0, locationSearchValue: ['汽油加氢装置'], location: '加氢装置', sampleRowSpan: 0, sampleSearchValue: ['C6-C8产品汽油'], sampleName: '加氢汽油', item: null, nameSearchValue: ['溴价'], name: '溴价/（g溴/100g油）' },
      { key: 33, locationRowSpan: 13, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 6, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['色度(Pt-Co)'], name: '色度/（Hazen单位-铂-钴号）' },
      { key: 34, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['异戊二烯'], name: '异戊二烯/ %（质量分数）' },
      { key: 35, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['炔烃'], name: '总炔/（mg/kg）' },
      { key: 36, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['二甲基甲酰胺'], name: '二甲基甲酰胺/（mg/kg）' },
      { key: 37, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['羰基化合物(以乙醛计)'], name: '硫含量/（mg/kg）' },
      { key: 38, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['异戊二烯'], sampleName: '异戊二烯', item: null, nameSearchValue: ['水'], name: '水含量/ %（质量分数）' },
      { key: 39, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 4, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['色度(Pt-Co)'], name: '色度/（Hazen单位-铂-钴号）' },
      { key: 40, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['间戊二烯'], name: '间戊二烯含量/ %（质量分数）' },
      { key: 41, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['环戊二烯+双环戊二烯'], name: '环戊二烯+双环戊二烯含量/ %（质量分数）' },
      { key: 42, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['间戊二烯'], sampleName: '间戊二烯', item: null, nameSearchValue: ['水'], name: '水含量/ %（质量分数）' },
      { key: 43, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 3, sampleSearchValue: ['双环戊二烯'], sampleName: '双环戊二烯', item: null, nameSearchValue: ['色度(Pt-Co)'], name: '色度/（Hazen单位-铂-钴号）' },
      { key: 44, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['双环戊二烯'], sampleName: '双环戊二烯', item: null, nameSearchValue: ['双环戊二烯'], name: '双环戊二烯/ %（质量分数）' },
      { key: 45, locationRowSpan: 0, locationSearchValue: ['碳五分离'], location: '碳五抽提装置', sampleRowSpan: 0, sampleSearchValue: ['双环戊二烯'], sampleName: '双环戊二烯', item: null, nameSearchValue: ['碳六及以下'], name: 'C6及以下/ %（质量分数）' },
      { key: 46, locationRowSpan: 11, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 6, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: null, nameSearchValue: ['乙二醇'], name: '乙二醇纯度/%（质量分数）' },
      { key: 47, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: null, nameSearchValue: ['水'], name: '水含量/%（质量分数）' },
      { key: 48, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: '紫外透光率/%', itemRowSpan: 3, nameSearchValue: ['紫外透过率(220nm)'], name: '220nm' },
      { key: 49, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: '紫外透光率/%', itemRowSpan: 0, nameSearchValue: ['紫外透过率(275nm)'], name: '275nm' },
      { key: 50, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: '紫外透光率/%', itemRowSpan: 0, nameSearchValue: ['紫外透过率(350nm)'], name: '350nm' },
      { key: 51, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['乙二醇产品'], sampleName: '乙二醇', item: null, nameSearchValue: ['醛(以甲醛计)'], name: '醛含量/（mg/kg）' },
      { key: 52, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 3, sampleSearchValue: ['二乙二醇产品'], sampleName: '二乙二醇', item: null, nameSearchValue: ['乙二醇'], name: '乙二醇含量/%（质量分数）' },
      { key: 53, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['二乙二醇产品'], sampleName: '二乙二醇', item: null, nameSearchValue: ['三乙二醇'], name: '三乙二醇含量/%（质量分数）' },
      { key: 54, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['二乙二醇产品'], sampleName: '二乙二醇', item: null, nameSearchValue: ['水'], name: '水含量/%（质量分数）' },
      { key: 55, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 2, sampleSearchValue: ['三乙二醇产品'], sampleName: '三乙二醇', item: null, nameSearchValue: ['二乙二醇'], name: '二乙二醇含量/%（质量分数）' },
      { key: 56, locationRowSpan: 0, locationSearchValue: ['EO／EG'], location: 'EOEG装置', sampleRowSpan: 0, sampleSearchValue: ['三乙二醇产品'], sampleName: '三乙二醇', item: null, nameSearchValue: ['多乙二醇'], name: '多乙二醇含量/%（质量分数）' },
    ],
    zhuangzhi: [
      { equipmentProductInfoID: 1, equipmentName: '裂解', inOutType: '投入', rawName: '石脑油', monthPlan: 157510, dayOver: 5531, monthOver: 126680, yieldPre: null, monthPre: 80.4 },
      { equipmentProductInfoID: 2, equipmentName: '裂解', inOutType: '投入', rawName: '加氢尾油', monthPlan: 32000, dayOver: 1140, monthOver: 25327, yieldPre: null, monthPre: 79.1 },
      { equipmentProductInfoID: 3, equipmentName: '裂解', inOutType: '投入', rawName: '饱和液化气', monthPlan: 29330, dayOver: 1021, monthOver: 20119, yieldPre: null, monthPre: 68.6 },
      { equipmentProductInfoID: 4, equipmentName: '裂解', inOutType: '投入', rawName: '碳五拔头油', monthPlan: 6000, dayOver: 0, monthOver: 2105, yieldPre: null, monthPre: 80.4 },
      { equipmentProductInfoID: 5, equipmentName: '裂解', inOutType: '投入', rawName: '富乙烯气', monthPlan: 3600, dayOver: 97, monthOver: 2315, yieldPre: null, monthPre: 64.3 },
      { equipmentProductInfoID: 6, equipmentName: '裂解', inOutType: '投入', rawName: '尾气', monthPlan: 3200, dayOver: 150, monthOver: 3066, yieldPre: null, monthPre: 95.8 },
      { equipmentProductInfoID: 7, equipmentName: '裂解', inOutType: '投入', rawName: '乙烷', monthPlan: 700, dayOver: 29, monthOver: 974, yieldPre: null, monthPre: 124.8 },
      { equipmentProductInfoID: 8, equipmentName: '裂解', inOutType: '产出', rawName: '氢气', monthPlan: 3369, dayOver: 118, monthOver: 2531, yieldPre: 1.48, monthPre: 75.1 },
      { equipmentProductInfoID: 9, equipmentName: '裂解', inOutType: '产出', rawName: '燃料气', monthPlan: 36710, dayOver: 1255, monthOver: 27845, yieldPre: 15.75, monthPre: 75.9 },
      { equipmentProductInfoID: 10, equipmentName: '汽油加氢', inOutType: '投入', rawName: '裂解汽油', monthPlan: 157510, dayOver: 5531, monthOver: 126680, yieldPre: null, monthPre: 80.4 },
      { equipmentProductInfoID: 11, equipmentName: '汽油加氢', inOutType: '投入', rawName: '氢气', monthPlan: 32000, dayOver: 1140, monthOver: 25327, yieldPre: null, monthPre: 79.1 },
      { equipmentProductInfoID: 12, equipmentName: '汽油加氢', inOutType: '产出', rawName: '加氢汽油', monthPlan: 3369, dayOver: 118, monthOver: 2531, yieldPre: 1.48, monthPre: 75.1 },
      { equipmentProductInfoID: 13, equipmentName: '汽油加氢', inOutType: '产出', rawName: '碳五', monthPlan: 36710, dayOver: 1255, monthOver: 27845, yieldPre: 15.75, monthPre: 75.9 },
    ],
    gasWaterBalance: [
      { gasWaterBalanceValueID: 0, rowItemName: '超高压蒸汽', colItemName: '热电联产外送量', collectValue: 202 },
      { gasWaterBalanceValueID: 9, rowItemName: '超高压蒸汽', colItemName: '减温减压器（转换输入）', collectValue: -11 },
      { gasWaterBalanceValueID: 10, rowItemName: '超高压蒸汽', colItemName: '减温减压器（转换输出）', collectValue: '/' },
      { gasWaterBalanceValueID: 11, rowItemName: '超高压蒸汽', colItemName: '乙烯及裂解汽油加氢', collectValue: -106 },
      { gasWaterBalanceValueID: 12, rowItemName: '超高压蒸汽', colItemName: 'EO/EG', collectValue: '/' },
      { gasWaterBalanceValueID: 13, rowItemName: '超高压蒸汽', colItemName: '芳烃抽提', collectValue: '/' },
      { gasWaterBalanceValueID: 14, rowItemName: '超高压蒸汽', colItemName: 'MTBE/丁烯-1', collectValue: '/' },
      { gasWaterBalanceValueID: 15, rowItemName: '超高压蒸汽', colItemName: 'HDPE', collectValue: '/' },
      { gasWaterBalanceValueID: 16, rowItemName: '超高压蒸汽', colItemName: 'LLDPE', collectValue: '/' },
      { gasWaterBalanceValueID: 17, rowItemName: '超高压蒸汽', colItemName: 'STPP/JPP', collectValue: '/' },
      { gasWaterBalanceValueID: 18, rowItemName: '超高压蒸汽', colItemName: '一循/三循', collectValue: '/' },
      { gasWaterBalanceValueID: 19, rowItemName: '超高压蒸汽', colItemName: '空分', collectValue: -83 },
      { gasWaterBalanceValueID: 20, rowItemName: '超高压蒸汽', colItemName: '鲁华', collectValue: '/' },
      { gasWaterBalanceValueID: 21, rowItemName: '超高压蒸汽', colItemName: '其他', collectValue: '/' },
      { gasWaterBalanceValueID: 22, rowItemName: '超高压蒸汽', colItemName: '平衡差量', collectValue: 2 },

      { gasWaterBalanceValueID: 0, rowItemName: '高压蒸汽', colItemName: '热电联产外送量', collectValue: 116 },
      { gasWaterBalanceValueID: 9, rowItemName: '高压蒸汽', colItemName: '减温减压器（转换输入）', collectValue: -5 },
      { gasWaterBalanceValueID: 10, rowItemName: '高压蒸汽', colItemName: '减温减压器（转换输出）', collectValue: 12 },
      { gasWaterBalanceValueID: 11, rowItemName: '高压蒸汽', colItemName: '乙烯及裂解汽油加氢', collectValue: -15 },
      { gasWaterBalanceValueID: 12, rowItemName: '高压蒸汽', colItemName: 'C5', collectValue: '/' },
      { gasWaterBalanceValueID: 12, rowItemName: '高压蒸汽', colItemName: 'EO/EG', collectValue: -41 },
      { gasWaterBalanceValueID: 13, rowItemName: '高压蒸汽', colItemName: '芳烃抽提', collectValue: -33 },
      { gasWaterBalanceValueID: 14, rowItemName: '高压蒸汽', colItemName: 'MTBE/丁烯-1', collectValue: '/' },
      { gasWaterBalanceValueID: 15, rowItemName: '高压蒸汽', colItemName: 'HDPE', collectValue: -2 },
      { gasWaterBalanceValueID: 16, rowItemName: '高压蒸汽', colItemName: 'LLDPE', collectValue: -1 },
      { gasWaterBalanceValueID: 17, rowItemName: '高压蒸汽', colItemName: 'STPP/JPP', collectValue: '/' },
      { gasWaterBalanceValueID: 18, rowItemName: '高压蒸汽', colItemName: '一循/三循', collectValue: -64 },
      { gasWaterBalanceValueID: 19, rowItemName: '高压蒸汽', colItemName: '空分', collectValue: 52 },
      { gasWaterBalanceValueID: 20, rowItemName: '高压蒸汽', colItemName: '鲁华', collectValue: -16 },
      { gasWaterBalanceValueID: 21, rowItemName: '高压蒸汽', colItemName: '其他', collectValue: '/' },
      { gasWaterBalanceValueID: 22, rowItemName: '高压蒸汽', colItemName: '平衡差量', collectValue: 3 },

      { gasWaterBalanceValueID: 6, rowItemName: '中压蒸汽', colItemName: '热电联产外送量', collectValue: 899 },
      { gasWaterBalanceValueID: 7, rowItemName: '中压蒸汽', colItemName: 'C5', collectValue: 2342 },
      { gasWaterBalanceValueID: 8, rowItemName: '中压蒸汽', colItemName: '丁二烯', collectValue: 645443 },
    ],
    proStatus: [
      { month: 5,
        equipmentProductInfoID: 1,
        resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' },
        monthOutput: 157.0000,
        dailyOutput: 157.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 157510.0000,
        productType: 1 },
      { month: 5,
        equipmentProductInfoID: 2,
        resRawMaterialInfo: { rawMaterialID: 2, code: '2', flashPoint: 0, burningTemperature: 0, rawCode: '2', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 2, rawMaterialName: '加氢尾油' },
        monthOutput: 1140.0000,
        dailyOutput: 1140.0000,
        baseOrganization:
            { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 32000.0000,
        productType: 1 },
      { month: 5, equipmentProductInfoID: 3, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 1021.0000, dailyOutput: 1021.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 29300.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 4, resRawMaterialInfo: { rawMaterialID: 4, code: '4', flashPoint: 0, burningTemperature: 0, rawCode: '4', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 4, rawMaterialName: '碳五拔头油' }, monthOutput: 12.0000, dailyOutput: 12.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 6000.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 5, resRawMaterialInfo: { rawMaterialID: 5, code: '5', flashPoint: 0, burningTemperature: 0, rawCode: '5', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 5, rawMaterialName: '富乙烯气' }, monthOutput: 79.0000, dailyOutput: 79.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 3600.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 6, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 150.0000, dailyOutput: 150.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 3200.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 7, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 29.0000, dailyOutput: 29.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 700.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 8, resRawMaterialInfo: { rawMaterialID: 8, code: '8', flashPoint: 0, burningTemperature: 0, rawCode: '8', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 8, rawMaterialName: '氢气' }, monthOutput: 118.0000, dailyOutput: 118.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 3369.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 9, resRawMaterialInfo: { rawMaterialID: 9, code: '9', flashPoint: 0, burningTemperature: 0, rawCode: '9', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 9, rawMaterialName: '燃料气' }, monthOutput: 1255.0000, dailyOutput: 1255.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 36710.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 10, resRawMaterialInfo: { rawMaterialID: 10, code: '10', flashPoint: 0, burningTemperature: 0, rawCode: '10', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 10, rawMaterialName: '乙烯' }, monthOutput: 2505.0000, dailyOutput: 2505.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 74000.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 11, resRawMaterialInfo: { rawMaterialID: 11, code: '11', flashPoint: 0, burningTemperature: 0, rawCode: '11', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 11, rawMaterialName: '丙烯' }, monthOutput: 1355.0000, dailyOutput: 1355.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 37871.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 12, resRawMaterialInfo: { rawMaterialID: 12, code: '12', flashPoint: 0, burningTemperature: 0, rawCode: '12', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 12, rawMaterialName: '混合碳四' }, monthOutput: 797.0000, dailyOutput: 797.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 23118.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 13, resRawMaterialInfo: { rawMaterialID: 13, code: '13', flashPoint: 0, burningTemperature: 0, rawCode: '13', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 13, rawMaterialName: '裂解汽油' }, monthOutput: 1641.0000, dailyOutput: 1641.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 47630.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 14, resRawMaterialInfo: { rawMaterialID: 14, code: '14', flashPoint: 0, burningTemperature: 0, rawCode: '14', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 14, rawMaterialName: '石油萘原料' }, monthOutput: 33.0000, dailyOutput: 33.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 1090.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 15, resRawMaterialInfo: { rawMaterialID: 15, code: '15', flashPoint: 0, burningTemperature: 0, rawCode: '15', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 15, rawMaterialName: '乙烯焦油' }, monthOutput: 275.0000, dailyOutput: 275.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 }, startTime: 1526389581000, monthPlan: 8132.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
            { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
            { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
      { month: 5, equipmentProductInfoID: 18, resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' }, monthOutput: 123.0000, dailyOutput: 123.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 4535.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 19, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 456.0000, dailyOutput: 456.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 3453.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 20, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 789.0000, dailyOutput: 789.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 345.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 21, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 117.0000, dailyOutput: 117.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 5345.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
          { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
      { month: 5, equipmentProductInfoID: 18, resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' }, monthOutput: 123.0000, dailyOutput: 123.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 4535.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 19, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 456.0000, dailyOutput: 456.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 3453.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 20, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 789.0000, dailyOutput: 789.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 345.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 21, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 117.0000, dailyOutput: 117.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 5345.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
          { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
      { month: 5, equipmentProductInfoID: 18, resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' }, monthOutput: 123.0000, dailyOutput: 123.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 4535.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 19, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 456.0000, dailyOutput: 456.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 3453.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 20, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 789.0000, dailyOutput: 789.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 345.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 21, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 117.0000, dailyOutput: 117.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 5345.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
          { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
      { month: 5, equipmentProductInfoID: 18, resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' }, monthOutput: 123.0000, dailyOutput: 123.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 4535.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 19, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 456.0000, dailyOutput: 456.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 3453.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 20, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 789.0000, dailyOutput: 789.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 345.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 21, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 117.0000, dailyOutput: 117.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 5345.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
          { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
      { month: 5, equipmentProductInfoID: 18, resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' }, monthOutput: 123.0000, dailyOutput: 123.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 4535.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 19, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 456.0000, dailyOutput: 456.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 3453.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 20, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 789.0000, dailyOutput: 789.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 345.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 21, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 117.0000, dailyOutput: 117.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 5345.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
          { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
      { month: 5, equipmentProductInfoID: 18, resRawMaterialInfo: { rawMaterialID: 1, code: '1', flashPoint: 0, burningTemperature: 0, rawCode: '1', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 1, rawMaterialName: '石脑油' }, monthOutput: 123.0000, dailyOutput: 123.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 4535.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 19, resRawMaterialInfo: { rawMaterialID: 3, code: '3', flashPoint: 0, burningTemperature: 0, rawCode: '3', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 3, rawMaterialName: '饱和液化气' }, monthOutput: 456.0000, dailyOutput: 456.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 3453.0000, productType: 1 },
      { month: 5, equipmentProductInfoID: 20, resRawMaterialInfo: { rawMaterialID: 6, code: '6', flashPoint: 0, burningTemperature: 0, rawCode: '6', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 6, rawMaterialName: '尾气' }, monthOutput: 789.0000, dailyOutput: 789.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 345.0000, productType: 2 },
      { month: 5, equipmentProductInfoID: 21, resRawMaterialInfo: { rawMaterialID: 7, code: '7', flashPoint: 0, burningTemperature: 0, rawCode: '7', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 7, rawMaterialName: '乙烷' }, monthOutput: 117.0000, dailyOutput: 117.0000, baseOrganization: { virtual: false, parentOrgnization: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '仓储管理', orgnizationCode: 'OU=仓储管理,OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1131 }, startTime: 1526389581000, monthPlan: 5345.0000, productType: 2 },
      { month: 5,
        equipmentProductInfoID: 16,
        resRawMaterialInfo:
          { rawMaterialID: 16, code: '16', flashPoint: 0, burningTemperature: 0, rawCode: '16', type: 'rawMaterial', boilingPoint: 0, formulaWeight: 0, key: 16, rawMaterialName: '污油' },
        monthOutput: 1.0000,
        dailyOutput: 1.0000,
        baseOrganization:
          { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 0.0000,
        productType: 2 },
      { month: 5,
        equipmentProductInfoID: 17,
        resRawMaterialInfo: { rawMaterialID: 17,
          code: '17',
          flashPoint: 0,
          burningTemperature: 0,
          rawCode: '17',
          type: 'rawMaterial',
          boilingPoint: 0,
          formulaWeight: 0,
          key: 17,
          rawMaterialName: '损失' },
        monthOutput: 5555.0000,
        dailyOutput: 5555.0000,
        baseOrganization: { virtual: false, parentOrgnization: 'OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', sortIndex: 0, children: [], orgnizationName: '17物质流通部', orgnizationCode: 'OU=17物质流通部,OU=ZHSH,OU=组织机构,DC=sinopec,DC=ad', orgnizationLevel: 0, enabled: false, orgID: 1130 },
        startTime: 1526389581000,
        monthPlan: 418.0000,
        productType: 2 },
    ],
    liejie: [
      { yuan: '乙烷', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '轻烃', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '加氢尾油', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '石脑油', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '石脑油', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '石脑油', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '石脑油', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10402', COT: '786', 负荷: '29', id: '4359', 天数: '75' },
      { yuan: '加氢尾油', collectTime: 'Tue May 15 09:58:52 CST 2018', stateID: '1', lu: 'GT-10405', COT: '806', 负荷: '46.5', id: '4360', 天数: '18' },
    ],
    redian: [
      { 产气量: '318', lu: 'GT-10415', 运行天数: '45', 主汽温度: '540' },
      { 产气量: '319', lu: 'GT-10416', 运行天数: '45', 主汽温度: '540' },
      { 产气量: '320', lu: 'GT-10417', 运行天数: '45', 主汽温度: '540' },
    ],
    fadian: [
      { 发电量: '60.01', lu: 'GT-10411', 运行天数: '157', 进气量: '370' },
      { 发电量: '53.95', lu: 'GT-10409', 运行天数: '20', 进气量: '389' },
      { 发电量: '54.95', lu: 'GT-10409', 运行天数: '20', 进气量: '389' },
    ],
    shengchan: [
      { reportDate: 1526389581000, productReportInfoID: 1, reportInfo: '乙烯装置：裂解炉负荷345吨/小时。' },
      { reportDate: 1526389581000, productReportInfoID: 2, reportInfo: '碳五装置：负荷9.6吨/小时' },
      { reportDate: 1526389581000, productReportInfoID: 3, reportInfo: '加氢装置：负荷70吨/小时。' },
    ],
    yuanliao: [
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '1', 罐存: '37485.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', productRawOfDayID: '1' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '2', 罐存: '4092.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '加氢尾油', productRawOfDayID: '2' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '3', 罐存: '3734.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '饱和液化气', productRawOfDayID: '3' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '4', 罐存: '2096.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', productRawOfDayID: '4' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '1', 罐存: '37485.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', productRawOfDayID: '1' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '2', 罐存: '4092.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '加氢尾油', productRawOfDayID: '2' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '3', 罐存: '3734.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '饱和液化气', productRawOfDayID: '3' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '4', 罐存: '2096.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', productRawOfDayID: '4' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '1', 罐存: '37485.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', productRawOfDayID: '1' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '2', 罐存: '4092.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '加氢尾油', productRawOfDayID: '2' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '3', 罐存: '3734.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '饱和液化气', productRawOfDayID: '3' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '4', 罐存: '2096.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', productRawOfDayID: '4' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '1', 罐存: '37485.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', productRawOfDayID: '1' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '2', 罐存: '4092.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '加氢尾油', productRawOfDayID: '2' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '3', 罐存: '3734.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '饱和液化气', productRawOfDayID: '3' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '4', 罐存: '2096.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', productRawOfDayID: '4' },
      { rawInfoType: '112.101', item: '罐存', rawMaterialID: '1', 罐存: '37485.0000', productRawInfoID: '1', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', productRawOfDayID: '1' },
    ],
    youji: [
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '4', 月出厂计划: '11111.0000', 罐存: '11111.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '碳五拔头油', 日出厂量: '123456.0000', productRawMonthID: '3', productRawOfDayID: '17' },
      { rawInfoType: '112.102', item: '月出厂计划', rawMaterialID: '1', 月出厂计划: '11000.0000', 罐存: '2201.0000', productRawInfoID: '3', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: '石脑油', 日出厂量: '9.0000', productRawMonthID: '1', productRawOfDayID: '7' },
    ],
    shuzhi: [
      { rawInfoType: '112.103', item: '月出厂计划', rawMaterialID: '6', 月出厂计划: '15830.0000', productRawInfoID: '8', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: 'HDPE（化销）', 厂内库存: '3739.0000', 日入库: '548.0000', 日出厂量: '716.0000', productRawMonthID: '2', productRawOfDayID: '10' },
      { rawInfoType: '112.103', item: '月出厂计划', rawMaterialID: '8', 月出厂计划: '15987.0000', productRawInfoID: '8', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: 'LLDPE（化销）', 厂内库存: '45645.0000', 日入库: '45648.0000', 日出厂量: '55555.0000', productRawMonthID: '4', productRawOfDayID: '20' },
      { rawInfoType: '112.103', item: '月出厂计划', rawMaterialID: '6', 月出厂计划: '15830.0000', productRawInfoID: '8', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: 'JPP（化销)', 厂内库存: '3739.0000', 日入库: '548.0000', 日出厂量: '716.0000', productRawMonthID: '2', productRawOfDayID: '10' },
      { rawInfoType: '112.104', item: '月出厂计划', rawMaterialID: '8', 月出厂计划: '15987.0000', productRawInfoID: '8', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: 'HDPE（SK）', 厂内库存: '45645.0000', 日入库: '45648.0000', 日出厂量: '55555.0000', productRawMonthID: '4', productRawOfDayID: '20' },
      { rawInfoType: '112.104', item: '月出厂计划', rawMaterialID: '6', 月出厂计划: '15830.0000', productRawInfoID: '8', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: 'STPP（SK）', 厂内库存: '3739.0000', 日入库: '548.0000', 日出厂量: '716.0000', productRawMonthID: '2', productRawOfDayID: '10' },
      { rawInfoType: '112.104', item: '月出厂计划', rawMaterialID: '8', 月出厂计划: '15987.0000', productRawInfoID: '8', startTime: 'Tue May 15 21:06:21 CST 2018', rawMaterialNam: 'JPP（SK）', 厂内库存: '45645.0000', 日入库: '45648.0000', 日出厂量: '55555.0000', productRawMonthID: '4', productRawOfDayID: '20' },
    ],
    dongli: [
      { totalValue: 294.0000, proPowerConsumeItem: { itemName: '发电量', unit: '万千瓦时/天', powerConsumeItemID: 2, powerConsumetype: 1 }, collectValue: 294.0000, powerConsumeValueID: 1, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 },
      { totalValue: 274.8000, proPowerConsumeItem: { itemName: '发电量', unit: '万千瓦时/天', powerConsumeItemID: 2, powerConsumetype: 1 }, collectValue: 274.8000, powerConsumeValueID: 2, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 },
      { totalValue: 16.2400, proPowerConsumeItem: { itemName: '外购电量', unit: '万千瓦时/天', powerConsumeItemID: 3, powerConsumetype: 1 }, collectValue: 16.2400, powerConsumeValueID: 3, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 },
      { totalValue: 3.3500, proPowerConsumeItem: { itemName: '天然气', unit: '万标方/天', powerConsumeItemID: 4, powerConsumetype: 1 }, collectValue: 3.3500, powerConsumeValueID: 4, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 },
      { totalValue: 2544.0000, proPowerConsumeItem: { itemName: '煤', unit: '吨/天', powerConsumeItemID: 5, powerConsumetype: 1 }, collectValue: 2544.0000, powerConsumeValueID: 5, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 },
      { totalValue: 944.0000, proPowerConsumeItem: { itemName: '卸煤', unit: '吨/天', powerConsumeItemID: 6, powerConsumetype: 1 }, collectValue: 944.0000, powerConsumeValueID: 6, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 },
      { totalValue: 17109.0000, proPowerConsumeItem: { itemName: '煤库存', unit: '吨', powerConsumeItemID: 7, powerConsumetype: 1 }, collectValue: 17109.0000, powerConsumeValueID: 7, proPowerConsumeEntry: { powerConsumeEntryID: 1, entryName: '用量' }, startDate: 1526389581000 }],
    shui: [
      { powerConsumeEntryID: 9, '碱浓度(<700)': 357.0000, itemName: '一循', powerConsumeItemID: 8, '钼酸根(0.8-1.5)': 1.5000, '用量(吨/时)': 47905.0000, powerConsumeValueID: 21, 'PH值(7.2-9.0)': 9.0000, '钙硬度(100-450)': 447.0000, '浓缩倍数(≥4)': 4.7000, '浊度(≤10)': 7.8600 },
      { powerConsumeEntryID: 9, '碱浓度(<700)': 359.0000, itemName: '二循', powerConsumeItemID: 8, '钼酸根(0.8-1.5)': 1.5000, '用量(吨/时)': 47905.0000, powerConsumeValueID: 21, 'PH值(7.2-9.0)': 9.0000, '钙硬度(100-450)': 447.0000, '浓缩倍数(≥4)': 4.7000, '浊度(≤10)': 7.8600 },
      { powerConsumeEntryID: 9, '碱浓度(<700)': 358.0000, itemName: '三循', powerConsumeItemID: 8, '钼酸根(0.8-1.5)': 1.5000, '用量(吨/时)': 47905.0000, powerConsumeValueID: 21, 'PH值(7.2-9.0)': 9.0000, '钙硬度(100-450)': 447.0000, '浓缩倍数(≥4)': 4.7000, '浊度(≤10)': 7.8600 },
    ],
    zhengqi: [
      { gasWaterBalanceValueID: 4, 中压蒸汽: 140.0000, itemType: 1, resourceID: 4359, 低压蒸汽: 0.0000, 高压蒸汽: 116.0000, resourceName: '热电联产外送量', 超高压蒸汽: 202.0000, startDate: 1526389581000 },
      { gasWaterBalanceValueID: 8, 中压蒸汽: 1232.0000, itemType: 1, resourceID: 4360, 低压蒸汽: 8888.0000, 高压蒸汽: 12354566.0000, resourceName: '减温减压器（转换输入）', 超高压蒸汽: 12356.0000, startDate: 1526389581000 },
    ],
    wushui: [
      { gasWaterBalanceValueID: 10, 低压氮气: 15778.0000, itemType: 2, resourceID: 48834, 生产污水: 0.0000, resourceName: '空分', startDate: 1526389581000 },
      { gasWaterBalanceValueID: 12, 低压氮气: 50.0000, itemType: 2, resourceID: 48843, 生产污水: 174.0000, resourceName: 'MTBE/丁烯-1', startDate: 1526389581000 },
    ],

  },
];
const a = [
  { reasourceName: '空分装置', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '220kv变电站', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '第二循环水场', planNum: parseInt(Math.random() * 10) },
  { reasourceName: 'C5分离装置', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '货运汽车停车场', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '丁二烯抽提装置', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '热电联产主装置', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '取水设施及净水场', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '发展用地1', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '55万吨/年裂解汽油加氢装置', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '全厂雨水提升泵站', planNum: parseInt(Math.random() * 10) },
  { reasourceName: '危险化学品库', planNum: parseInt(Math.random() * 10) },
];
